/*
Comprehensive aerial imagery metadata - PURE DATA, NO DEPENDENCIES
Each record contains all properties needed to construct the appropriate layer type
Use durm_aerials.js to parse this metadata and create actual layer instances
*/

define([], function() {
    return {
        // Master list of all aerial layers in chronological order
        webgis2: [
        // ============= NON-NEARMAP LAYERS =============
        {
            id: "aerials1940",
            title: "1940 Aerial Photos (City Only)",
            sortDate: "1940-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1940/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "soils1983",
            title: "1983 Aerial Photos, with stream delination and soils",
            sortDate: "1983-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1983/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials1988",
            title: "1988 Aerial Photos (County Only)",
            sortDate: "1988-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1988/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials1994",
            title: "1994 Aerial Photos (City Only)",
            sortDate: "1994-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1994/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials1999",
            title: "1999 Aerial Photos",
            sortDate: "1999-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1999/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2002",
            title: "2002 Aerial Photos",
            sortDate: "2002-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2002/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2005",
            title: "2005 Aerial Photos",
            sortDate: "2005-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2005/MapServer",
            icon: "NC",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2007",
            title: "2007 Satellite Photos",
            sortDate: "2007-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2007/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2008",
            title: "2008 Satellite Photos",
            sortDate: "2008-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2008/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2008_ir",
            title: "2008 Color-infrared Satellite Photos",
            sortDate: "2008-01-15",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2008_ColorIR/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2008",
            title: "2008 Aerial Photos (NAIP)",
            sortDate: "2008-06-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2008/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2009",
            title: "2009 Satellite Photos",
            sortDate: "2009-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2009/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2010",
            title: "2010 Satellite Photos",
            sortDate: "2010-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2010/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2010",
            title: "2010 Aerial Photos",
            sortDate: "2010-06-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2010/MapServer",
            icon: "NC",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2011",
            title: "2011 Satellite Photos",
            sortDate: "2011-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2011/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2012",
            title: "2012 Satellite Photos",
            sortDate: "2012-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2012/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2013",
            title: "2013 Satellite Photos",
            sortDate: "2013-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2013/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2013",
            title: "2013 Aerial Photos",
            sortDate: "2013-06-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2013/MapServer",
            icon: "NC",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2014",
            title: "2014 Satellite Photos",
            sortDate: "2014-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2014/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2015",
            title: "2015 Satellite Photos",
            sortDate: "2015-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2015/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2016",
            title: "2016 Satellite Photos",
            sortDate: "2016-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2016/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2017",
            title: "2017 Aerial Photos",
            sortDate: "2017-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2017/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2019",
            title: "2019 Aerial Photos",
            sortDate: "2019-01-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2019/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2021",
            title: "2021 Aerial Photos",
            sortDate: "2021-04-01",
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2021/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
    ]
    };
});
