/*
Comprehensive aerial imagery metadata - PURE DATA, NO DEPENDENCIES
Each record contains all properties needed to construct the appropriate layer type
Use durm_aerials.js to parse this metadata and create actual layer instances
*/

define([], function() {
    return {
        // Master list of all aerial layers in chronological order
        webgis2: [
        // ============= NON-NEARMAP LAYERS =============
        {
            id: "aerials1940",
            title: "1940 Aerial Photos (City Only)",
            sortDate: "1940-01-01",
            sliderIndex: 0,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1940/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "soils1983",
            title: "1983 Aerial Photos, with stream delination and soils",
            sortDate: "1983-01-01",
            sliderIndex: 1,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1983/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials1988",
            title: "1988 Aerial Photos (County Only)",
            sortDate: "1988-01-01",
            sliderIndex: 2,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1988/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials1994",
            title: "1994 Aerial Photos (City Only)",
            sortDate: "1994-01-01",
            sliderIndex: 3,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1994/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials1999",
            title: "1999 Aerial Photos",
            sortDate: "1999-01-01",
            sliderIndex: 4,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho1999/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2002",
            title: "2002 Aerial Photos",
            sortDate: "2002-01-01",
            sliderIndex: 5,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2002/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2005",
            title: "2005 Aerial Photos",
            sortDate: "2005-01-01",
            sliderIndex: 6,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2005/MapServer",
            icon: "NC",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2007",
            title: "2007 Satellite Photos",
            sortDate: "2007-01-01",
            sliderIndex: 7,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2007/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2008",
            title: "2008 Satellite Photos",
            sortDate: "2008-01-01",
            sliderIndex: 8,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2008/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2008_ir",
            title: "2008 Color-infrared Satellite Photos",
            sortDate: "2008-01-15",
            sliderIndex: null,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2008_ColorIR/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2008",
            title: "2008 Aerial Photos (NAIP)",
            sortDate: "2008-06-01",
            sliderIndex: 9,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2008/MapServer",
            icon: "USA",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2009",
            title: "2009 Satellite Photos",
            sortDate: "2009-01-01",
            sliderIndex: 10,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2009/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2010",
            title: "2010 Satellite Photos",
            sortDate: "2010-01-01",
            sliderIndex: 11,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2010/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2010",
            title: "2010 Aerial Photos",
            sortDate: "2010-06-01",
            sliderIndex: 12,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2010/MapServer",
            icon: "NC",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2011",
            title: "2011 Satellite Photos",
            sortDate: "2011-01-01",
            sliderIndex: 13,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2011/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2012",
            title: "2012 Satellite Photos",
            sortDate: "2012-01-01",
            sliderIndex: 14,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2012/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2013",
            title: "2013 Satellite Photos",
            sortDate: "2013-01-01",
            sliderIndex: 15,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2013/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "aerials2013",
            title: "2013 Aerial Photos",
            sortDate: "2013-06-01",
            sliderIndex: 16,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2013/MapServer",
            icon: "NC",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2014",
            title: "2014 Satellite Photos",
            sortDate: "2014-01-01",
            sliderIndex: 17,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2014/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "satellite2015",
            title: "2015 Satellite Photos",
            sortDate: "2015-01-01",
            sliderIndex: 19,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2015/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        }
    ],
    nearmap: [
        // ============= NEARMAP LAYERS =============
        {
            id: "nearmap2014",
            title: "2014 Nearmap Aerials, Oct-Nov",
            sortDate: "2014-10-15",
            sliderIndex: 18,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2014-10-01 20:10:05' AND TIMESTAMP '2014-11-29 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2015_spring",
            title: "2015 Nearmap Aerials, Mar",
            sortDate: "2015-03-15",
            sliderIndex: 20,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2015-03-01 20:10:05' AND TIMESTAMP '2015-03-29 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2015_fall",
            title: "2015 Nearmap Aerials, Nov",
            sortDate: "2015-11-15",
            sliderIndex: 21,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2015-11-01 20:10:05' AND TIMESTAMP '2015-11-29 20:20:20'",
            isNearmap: true
        },

        {
            id: "satellite2016",
            title: "2016 Satellite Photos",
            sortDate: "2016-01-01",
            sliderIndex: 22,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Satellite2016/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "nearmap2016_spring",
            title: "2016 Nearmap Aerials, Feb-Mar",
            sortDate: "2016-02-15",
            sliderIndex: 23,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2016-02-01 20:10:05' AND TIMESTAMP '2016-03-29 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2016_fall",
            title: "2016 Nearmap Aerials, Sep",
            sortDate: "2016-09-15",
            sliderIndex: 24,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2016-09-01 20:10:05' AND TIMESTAMP '2016-09-29 20:20:20'",
            isNearmap: true
        },

        {
            id: "aerials2017",
            title: "2017 Aerial Photos",
            sortDate: "2017-01-01",
            sliderIndex: 25,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2017/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "nearmap2017_spring1",
            title: "2017 Nearmap Aerials, Jan-Feb",
            sortDate: "2017-02-01",
            sliderIndex: 26,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2017-01-01 20:10:05' AND TIMESTAMP '2017-03-29 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2017_spring2",
            title: "2017 Nearmap Aerials, May",
            sortDate: "2017-05-15",
            sliderIndex: 27,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2017-05-01 20:10:05' AND TIMESTAMP '2017-05-29 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2017_fall",
            title: "2017 Nearmap Aerials, Sep-Nov",
            sortDate: "2017-10-15",
            sliderIndex: 28,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2017-09-01 20:10:05' AND TIMESTAMP '2017-11-29 20:20:20'",
            isNearmap: true
        },

        {
            id: "nearmap2018_spring",
            title: "2018 Nearmap Aerials, Jan-Feb",
            sortDate: "2018-01-15",
            sliderIndex: 29,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2018-01-01 20:10:05' AND TIMESTAMP '2018-02-26 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2018_fall",
            title: "2018 Nearmap Aerials, Sep-Oct",
            sortDate: "2018-09-15",
            sliderIndex: 30,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2018-09-01 20:10:05' AND TIMESTAMP '2018-11-01 20:20:20'",
            isNearmap: true
        },

        {
            id: "aerials2019",
            title: "2019 Aerial Photos",
            sortDate: "2019-01-01",
            sliderIndex: 31,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2019/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "nearmap2019_spring1",
            title: "2019 Nearmap Aerials, Jan",
            sortDate: "2019-01-15",
            sliderIndex: 32,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2019-01-01 20:10:05' AND TIMESTAMP '2019-02-01 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2019_spring2",
            title: "2019 Nearmap Aerials, May",
            sortDate: "2019-05-15",
            sliderIndex: 33,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2019-05-01 20:10:05' AND TIMESTAMP '2019-06-01 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2019_fall",
            title: "2019 Nearmap Aerials, Oct-Nov",
            sortDate: "2019-10-15",
            sliderIndex: 34,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2019-10-01 20:10:05' AND TIMESTAMP '2019-12-01 20:20:20'",
            isNearmap: true
        },

        {
            id: "nearmap2020_spring1",
            title: "2020 Nearmap Aerials, Jan",
            sortDate: "2020-01-15",
            sliderIndex: 35,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2020-01-01 20:10:05' AND TIMESTAMP '2020-02-02 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2020_spring2",
            title: "2020 Nearmap Aerials, May-Jun",
            sortDate: "2020-05-15",
            sliderIndex: 36,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2020-05-01 20:10:05' AND TIMESTAMP '2020-07-02 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2020_fall",
            title: "2020 Nearmap Aerials, Sep",
            sortDate: "2020-09-15",
            sliderIndex: 37,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2020-09-01 20:10:05' AND TIMESTAMP '2020-10-02 20:20:20'",
            isNearmap: true
        },

        {
            id: "nearmap2021_spring1",
            title: "2021 Nearmap Aerials, Jan",
            sortDate: "2021-01-15",
            sliderIndex: 38,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2021-01-01 20:10:05' AND TIMESTAMP '2021-02-05 20:20:20'",
            isNearmap: true
        },
        {
            id: "aerials2021",
            title: "2021 Aerial Photos",
            sortDate: "2021-04-01",
            sliderIndex: 39,
            layerType: "TileLayer",
            loadingtype: "enterprisetile",
            url: "https://webgis2.durhamnc.gov/server/rest/services/Rasters/Ortho2021/MapServer",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 2,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            isNearmap: false
        },
        {
            id: "nearmap2021_spring2",
            title: "2021 Nearmap Aerials, May",
            sortDate: "2021-05-15",
            sliderIndex: null,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2021-05-01 20:10:05' AND TIMESTAMP '2021-06-05 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2021_fall",
            title: "2021 Nearmap Aerials, Nov",
            sortDate: "2021-11-15",
            sliderIndex: 40,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2021-11-01 20:10:05' AND TIMESTAMP '2021-12-01 20:20:20'",
            isNearmap: true
        },

        {
            id: "nearmap2022_spring1",
            title: "2022 Nearmap Aerials, Feb",
            sortDate: "2022-02-04",
            sliderIndex: 41,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2022-02-01 20:10:05' AND TIMESTAMP '2022-02-07 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2022_spring2",
            title: "2022 Nearmap Aerials, May",
            sortDate: "2022-05-15",
            sliderIndex: 42,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2022-05-01 20:10:05' AND TIMESTAMP '2022-07-01 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2022_fall",
            title: "2022 Nearmap Aerials, Oct",
            sortDate: "2022-10-17",
            sliderIndex: 43,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2022-10-16 20:10:05' AND TIMESTAMP '2022-10-19 20:20:20'",
            isNearmap: true
        },

        {
            id: "nearmap2023_winter",
            title: "2023 Nearmap Aerials, Jan",
            sortDate: "2023-01-25",
            sliderIndex: 44,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2023-01-22 20:10:05' AND TIMESTAMP '2023-01-28 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2023_spring",
            title: "2023 Nearmap Aerials, May",
            sortDate: "2023-05-07",
            sliderIndex: 45,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2023-05-04 20:10:05' AND TIMESTAMP '2023-05-11 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2023_fall",
            title: "2023 Nearmap Aerials, October",
            sortDate: "2023-10-15",
            sliderIndex: 46,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2023-10-01 20:10:05' AND TIMESTAMP '2023-10-29 20:20:20'",
            isNearmap: true
        },

        {
            id: "nearmap2024_spring",
            title: "2024 Nearmap Aerials, February",
            sortDate: "2024-02-05",
            sliderIndex: 47,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2024-01-26 20:10:05' AND TIMESTAMP '2024-02-15 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2024_summer",
            title: "2024 Nearmap Aerials, May",
            sortDate: "2024-05-29",
            sliderIndex: 48,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2024-05-27 20:10:05' AND TIMESTAMP '2024-06-01 20:20:20'",
            isNearmap: true
        },
        {
            id: "nearmap2024_fall",
            title: "2024 Nearmap Aerials, Oct",
            sortDate: "2024-10-30",
            sliderIndex: 49,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2024-10-20 20:10:05' AND TIMESTAMP '2024-11-10 20:20:20'",
            isNearmap: true
        },

        {
            id: "nearmap2025_winter",
            title: "2025 Nearmap Aerials, Jan",
            sortDate: "2025-01-27",
            sliderIndex: 50,
            layerType: "ImageryLayer",
            loadingtype: "nearmap",
            url: "NEARMAP_URL",
            icon: "DUR",
            listMode: "hide",
            listcategory: "Aerial Photos, Historical",
            layer_order: 0,
            lyr_zindex: 1,
            visible: false,
            legendEnabled: false,
            popupEnabled: false,
            opacity: 1,
            minScale: 0,
            maxScale: 564,
            definitionExpression: "acquisitiondate BETWEEN TIMESTAMP '2025-1-25 20:10:05' AND TIMESTAMP '2025-1-30 20:20:20'",
            isNearmap: true
        }
    ]
    };
});
